# Generated by Django 3.0.3 on 2020-08-30 12:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('date', models.DateField(default=datetime.datetime(2020, 8, 30, 12, 39, 49, 134108, tzinfo=utc))),
                ('content', models.TextField()),
            ],
        ),
    ]
